#!/usr/bin/env zsh

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function replace_tag_in_file(){
  python -c "s=open('$3', 'r').read().replace('$1','$2'); open('$3', 'w').write(s)" 2>&1 >/dev/null
}
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv activate neovim2
neovim2_py=`pyenv which python`  # Note the path
pyenv activate neovim3
neovim3_py=`pyenv which python`  # Note the path

replace_tag_in_file '<<nvimpy2>>' $neovim2_py "$HOME/.config/nvim/init.vim"
replace_tag_in_file '<<nvimpy3>>' $neovim3_py "$HOME/.config/nvim/init.vim"

# share configs between vim and neovim
mkdir -p ~/.local/share/nvim/site
ln -s ~/.local/share/nvim/site ~/.vim 
rm ~/.vimrc
ln -s ~/.config/nvim/init.vim ~/.vimrc


yes | $(brew --prefix)/opt/fzf/install --all
echo "Stowing all files"
echo "------------------"
CURRENT = `pwd`
cd $MYDIR/base
./stowall
cd $CURRENT

case "$(uname -s)" in
   Darwin)
	CURRENT = `pwd`
	cd $MYDIR/mac
	./stowall
	cd $CURRENT
    ;;
   Linux)
	CURRENT = `pwd`
	cd $MYDIR/linux
	./stowall
	cd $CURRENT
	test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
	test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
	test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
	echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
	zsh
	test -r ~/.postzsh && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.postzsh
	echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
	echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.zprofile
    ;;
esac

echo "Sourcing all files"
echo "------------------"
mkdir $HOME/.vim/doc 2>&1 >/dev/null
#vim --cmd "helptags $HOME/.vim/doc" --cmd "q"
[ -f  ~/.bash_profile ] && source ~/.bash_profile
[ -f  ~/.bashrc ] && source ~/.bashrc
[ -f  ~/.zshrc ] && source ~/.zshrc



