#!/usr/bin/env sh

#export JAVA_HOME=$(/usr/libexec/java_home)
#export PATH=${JAVA_HOME}/bin:$PATH
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH=$HOME/bin:$HOME/sbin:$HOME/bin-this:$PATH
export PYENV_ROOT=$HOME/.pyenv
export _Z_DATA="$HOME/.z-data"
export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATIO="en_US.UTFUTF"
export LC_ALL="en_US.UTF-8"

export HISTSIZE=1000000
export HISTFILESIZE=1000000000
export SAVEHIST=10000


export FZF_DEFAULT_OPTS='--height 40% --reverse --border --ansi'
export FZF_DEFAULT_COMMAND='fd --type file --follow  --color=always --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


export PATH="~/.pyenv/bin:$PATH"
export PATH="$PATH:."




