#! /usr/bin/env zsh
# Source any other dot files
# Just .aliases right now git-completion.bash
for file in ~/.{aliases,prompt}; do
  [ -r "$file" ] && source "$file"
done
autoload -U promptinit; promptinit
unset file
bindkey -v
# Disable zsh autocorrect
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt completeinword
zstyle ':completion:*:*:git:*' script /usr/local/etc/bash_completion.d/git-completion.bash

# set editing-mode vi
set blink-matching-paren on

#fpath=(/usr/local/share/zsh-completions $fpath)
#autoload -U compinit && compinit
#zmodload -i zsh/complist
#compinit -d ~/.zcompdump_capture

# . <(npm completion)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
#antigen bundle marzocchi/zsh-notify
antigen bundle mafredri/zsh-async
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
#antigen theme robbyrussell
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

source ~/.z/z.sh
#alias journal=~/.journal.sh

#zstyle ':notify:*' command-complete-timeout 5
#zstyle ':notify:*' error-icon "https://media3.giphy.com/media/10ECejNtM1GyRy/200_s.gif"
#zstyle ':notify:*' error-title "Fail"
#zstyle ':notify:*' success-icon "https://s-media-cache-ak0.pinimg.com/564x/b5/5a/18/b55a1805f5650495a74202279036ecd2.jpg"
#zstyle ':notify:*' success-title "Success"


# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

[[ -e "$HOME/anaconda/bin/activate.sh" ]] && source "$HOME/anaconda/bin/activate.sh"
[[ -e "$HOME/anaconda3/bin/activate.sh" ]] && source "$HOME/anaconda3/bin/activate.sh"
