require('yasser.globals')
require('impatient')
require('yasser.plugins')
require('packer_compiled')
require('yasser.settings')
require('yasser.keymappings')
require('yasser.autocommands')
require('yasser.theme.colorscheme')
-- vimscipt only plugins and helpers
vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
vim.cmd('source ~/.config/nvim/vimscript/markdown.vim')
vim.cmd('source ~/.config/nvim/vimscript/grammarous.vim')
vim.cmd('source ~/.config/nvim/vimscript/tex.vim')
if vim.g.started_by_firenvim then
    vim.cmd('source ~/.config/nvim/vimscript/firenvim.vim')
else
    vim.cmd('source ~/.config/nvim/vimscript/context.vim')
    vim.cmd('source ~/.config/nvim/vimscript/ctrls.vim')
end
-- vim.cmd('source ~/.config/nvim/vimscript/ultisnips.vim')

-- LSP
require('yasser.lsp')
-- require('yasser.lsp.php-ls')
-- require('yasser.lsp.lua-ls')
-- require('yasser.lsp.bash-ls')
-- require('yasser.lsp.python-ls')
-- require('yasser.lsp.yaml-ls')
-- require('yasser.lsp.vim-ls')
-- require('yasser.lsp.html-ls')
-- require('yasser.lsp.css-ls')
-- require('yasser.lsp.latex-ls')
-- require('yasser.lsp.json-ls')
-- require('lsp.efm-general-ls')
-- require('lsp.clangd')
-- require('lsp.dart-ls')
-- require('lsp.go-ls')
-- require('lsp.js-ts-ls')
-- require('lsp.rust-ls')
-- require('lsp.terraform-ls')
-- require('lsp.graphql-ls')
-- require('lsp.docker-ls')
-- require('lsp.emmet-ls')
-- require('lsp.svelte-ls')
-- require('lsp.tailwindcss-ls')
-- require('lsp.ruby-ls')
-- require('lsp.kotlin-ls')

