return {}
-- return {
-- 	"zbirenbaum/neodim",
-- 	event = "LspAttach",
-- 	config = function()
-- 		require("neodim").setup({
-- 			refresh_delay = 75,
-- 			alpha = 0.5,
-- 			blend_color = "#10171f",
-- 			hide = {
-- 				underline = true,
-- 				virtual_text = true,
-- 				signs = false,
-- 			},
-- 			regex = {
-- 				"[uU]nused",
-- 				"[nN]ot accessed",
-- 				"[nN]ever [rR]ead",
-- 				"[nN]ot [rR]ead",
-- 			},
-- 			priority = 128,
-- 			disable = {},
-- 		})
-- 	end,
-- }
--
-- return {
-- 	"askfiy/lsp_extra_dim",
-- 	event = { "LspAttach" },
-- 	config = function()
-- 		require("lsp_extra_dim").setup({
-- 			disable_diagnostic_style = {},
-- 		})
-- 	end,
-- }
