#!/bin/bash

################################################################################
# add_to_ignore.sh
# 
# Helper script to add repositories to the git backup ignore list
#
# DESCRIPTION:
#   This script adds repository paths to ~/.git_repos_ignore so they will be
#   skipped by update_git_repos.sh. Useful for external repos you don't want
#   to manage or repos with issues.
#
# USAGE:
#   ./add_to_ignore.sh <repo_path>
#
# ARGUMENTS:
#   repo_path - Path to repository (relative to ~/code or absolute path)
#
# EXAMPLES:
#   ./add_to_ignore.sh papers/students/yomnathesis
#   ./add_to_ignore.sh /Users/yasser/code/old-project/repo
#   ./add_to_ignore.sh learning
#
# FILES:
#   ~/.git_repos_ignore - The ignore list file (created if doesn't exist)
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23
################################################################################

set -e

# Configuration - all paths use $HOME, works from any directory
IGNORE_FILE="$HOME/.git_repos_ignore"
CODE_DIR="$HOME/code"

# Show usage if no arguments provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <repo_path>"
    echo ""
    echo "Examples:"
    echo "  $0 papers/students/yomnathesis"
    echo "  $0 /Users/yasser/code/old-project/repo"
    echo "  $0 learning"
    echo ""
    echo "Current ignore list:"
    if [ -f "$IGNORE_FILE" ]; then
        grep -v '^#' "$IGNORE_FILE" | grep -v '^[[:space:]]*$' || echo "  (empty)"
    else
        echo "  (file doesn't exist yet)"
    fi
    exit 1
fi

repo_input="$1"

# Convert absolute path to relative if needed
if [[ "$repo_input" == "$CODE_DIR"* ]]; then
    relative_path="${repo_input#$CODE_DIR/}"
else
    relative_path="$repo_input"
fi

# Create ignore file if it doesn't exist
if [ ! -f "$IGNORE_FILE" ]; then
    cat > "$IGNORE_FILE" << 'EOF'
# Git repositories ignore list
# Add repository paths (relative to $HOME/code) that should be skipped
# One path per line, comments start with #

EOF
fi

# Check if already in ignore list
if grep -qxF "$relative_path" "$IGNORE_FILE" 2>/dev/null; then
    echo "Repository already in ignore list: $relative_path"
    exit 0
fi

# Add to ignore list
echo "$relative_path" >> "$IGNORE_FILE"
echo "✓ Added to ignore list: $relative_path"
echo ""
echo "Current ignore list:"
grep -v '^#' "$IGNORE_FILE" | grep -v '^[[:space:]]*$'
