#!/bin/bash

################################################################################
# backup.sh
# 
# Master backup orchestration script
#
# DESCRIPTION:
#   Runs the complete backup workflow in 4 steps:
#   1. Updates all git repositories (commits, pushes, migrates)
#   2. Generates restoration scripts for Linux/macOS/Windows
#   3. Backs up all scripts to iCloud
#   4. Syncs important folders to iCloud with rsync
#
# FEATURES:
#   ✓ Fully automated workflow
#   ✓ Time tracking (shows elapsed time)
#   ✓ Comprehensive folder syncing
#   ✓ Excludes build artifacts and dependencies
#   ✓ iCloud integration
#
# USAGE:
#   ./backup.sh
#
# WHAT GETS BACKED UP:
#   Git Repositories:
#     - All repos under ~/code (pushed to GitHub)
#     - External repos backed up separately
#   
#   Scripts:
#     - All .sh files from ~
#     - All .bat files (generated restore scripts)
#     - Configuration files (~/.git_repos_ignore)
#   
#   Folders synced to iCloud:
#     - ~/.ssh (SSH keys and config)
#     - ~/.config (application configs)
#     - ~/.copilot (Copilot settings)
#     - ~/bin (custom scripts)
#     - ~/Desktop
#     - ~/Downloads
#     - ~/code (all repositories)
#     - ~/koshodojo
#     - ~/negmas
#     - ~/.secrets
#
# BACKUP LOCATION:
#   ~/Documents/MacBackup/ (iCloud synced)
#
# REQUIREMENTS:
#   - git
#   - gh (GitHub CLI)
#   - rsync
#   - iCloud configured and syncing
#
# TIME ESTIMATE:
#   Depends on number of repos and folder sizes
#   Typically: 10-60 minutes
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23
################################################################################


# Record start time
START_TIME=$(date +%s)

# Target path inside iCloud
ICLOUD_BACKUP_PATH="$HOME/Documents/MacBackup"

# Git management scripts to backup
GIT_SCRIPTS=(
    "$HOME/update_git_repos.sh"
    "$HOME/generate_restore_script.sh"
    "$HOME/backup.sh"
    "$HOME/add_to_ignore.sh"
)

# Git management configuration files to backup
GIT_CONFIG_FILES=(
    "$HOME/.git_repos_ignore"
)

# Folders to sync
FOLDERS_TO_SYNC=(
    "$HOME/.ssh"
    "$HOME/.config"
    "$HOME/.copilot"
    "$HOME/bin"
    "$HOME/Desktop"
    "$HOME/Downloads"
    "$HOME/code"
    "$HOME/koshodojo"
    "$HOME/negmas"
    "$HOME/.secrets"
)

mkdir -p "$ICLOUD_BACKUP_PATH"

echo "Starting backup and sync process..."
echo ""

# Step 1: Run update_git_repos.sh to update all git repositories
echo "═══════════════════════════════════════════════════════════════"
echo "Step 1: Running Git Repository Updates..."
echo "═══════════════════════════════════════════════════════════════"
echo ""

UPDATE_SCRIPT="$HOME/update_git_repos.sh"
if [ -f "$UPDATE_SCRIPT" ]; then
    "$UPDATE_SCRIPT"
else
    echo "Warning: update_git_repos.sh not found at $UPDATE_SCRIPT"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Step 2: Generating Restoration Script..."
echo "═══════════════════════════════════════════════════════════════"
echo ""

GENERATE_SCRIPT="$HOME/generate_restore_script.sh"
if [ -f "$GENERATE_SCRIPT" ]; then
    "$GENERATE_SCRIPT"
    echo ""
    echo "✓ Generated restoration scripts"
else
    echo "Warning: generate_restore_script.sh not found at $GENERATE_SCRIPT"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Step 3: Backing Up Scripts to iCloud..."
echo "═══════════════════════════════════════════════════════════════"

# Backup git management scripts to a dedicated folder
SCRIPTS_BACKUP_DIR="$ICLOUD_BACKUP_PATH/git_management_scripts"
mkdir -p "$SCRIPTS_BACKUP_DIR"

echo ""
echo "Backing up shell scripts and configuration files..."
scripts_backed_up=0

# Backup all .sh files from home directory
echo "  Scanning for .sh files in home directory..."
for SCRIPT in "$HOME"/*.sh; do
    if [ -f "$SCRIPT" ]; then
        SCRIPT_NAME=$(basename "$SCRIPT")
        cp "$SCRIPT" "$SCRIPTS_BACKUP_DIR/"
        echo "  ✓ Backed up: $SCRIPT_NAME"
        ((scripts_backed_up++))
    fi
done

# Backup configuration files
for CONFIG in "${GIT_CONFIG_FILES[@]}"; do
    if [ -f "$CONFIG" ]; then
        CONFIG_NAME=$(basename "$CONFIG")
        cp "$CONFIG" "$SCRIPTS_BACKUP_DIR/"
        echo "  ✓ Backed up: $CONFIG_NAME"
        ((scripts_backed_up++))
    fi
done

# Backup generated restoration scripts (.bat for Windows)
if [ -f "$HOME/restore_git_repos.bat" ]; then
    cp "$HOME/restore_git_repos.bat" "$SCRIPTS_BACKUP_DIR/"
    echo "  ✓ Backed up: restore_git_repos.bat"
    ((scripts_backed_up++))
fi

# Create a timestamp file
echo "Backup created: $(date '+%Y-%m-%d %H:%M:%S')" > "$SCRIPTS_BACKUP_DIR/BACKUP_TIMESTAMP.txt"
echo "Shell scripts and config files backed up: $scripts_backed_up" >> "$SCRIPTS_BACKUP_DIR/BACKUP_TIMESTAMP.txt"

echo ""
echo "Shell scripts backup complete ($scripts_backed_up files)"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Step 4: Syncing Folders to iCloud..."
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Now sync folders
for FOLDER in "${FOLDERS_TO_SYNC[@]}"; do
    if [ -d "$FOLDER" ]; then
        FOLDER_NAME=$(basename "$FOLDER")
        echo "Syncing $FOLDER_NAME..."
        
        # rsync flags:
        # -a: Archive (preserves permissions/timestamps)
        # -v: Verbose
        # -z: Compress
        # -L: Follow symlinks (crucial for Windows readability later)
        # --delete: Mirror deletions from source to backup
        rsync -avzL --delete \
            --exclude 'node_modules/' \
            --exclude '.git/' \
            --exclude '.svn/' \
            --exclude '.hg/' \
            --exclude 'target/' \
            --exclude 'dist/' \
            --exclude 'build/' \
            --exclude 'out/' \
            --exclude '.next/' \
            --exclude '.nuxt/' \
            --exclude '.venv/' \
            --exclude 'venv/' \
            --exclude '__pycache__/' \
            --exclude '.terraform/' \
            --exclude '.DS_Store' \
            --exclude '*.log' \
            --exclude 'tmp/' \
            "$FOLDER/" "$ICLOUD_BACKUP_PATH/$FOLDER_NAME/"
    else
        echo "Warning: $FOLDER not found, skipping."
    fi
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "All operations complete!"
echo "═══════════════════════════════════════════════════════════════"

# Calculate elapsed time
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))
HOURS=$((ELAPSED / 3600))
MINUTES=$(((ELAPSED % 3600) / 60))
SECONDS=$((ELAPSED % 60))

echo ""
echo "Summary:"
echo "  ✓ Git repositories updated and pushed"
echo "  ✓ Restoration script generated"
echo "  ✓ Scripts backed up to iCloud"
echo "  ✓ Folders synced to iCloud"
echo ""
echo "Time taken:"
if [ $HOURS -gt 0 ]; then
    printf "  ⏱  %02d:%02d:%02d (HH:MM:SS)\n" $HOURS $MINUTES $SECONDS
else
    printf "  ⏱  %02d:%02d (MM:SS)\n" $MINUTES $SECONDS
fi
echo ""
echo "Check iCloud status in Finder."
