#!/bin/bash

################################################################################
# generate_restore_script.sh
# 
# Generates cross-platform restoration scripts for all git repositories
#
# DESCRIPTION:
#   Scans ~/code for all git repositories with remotes and generates two
#   restoration scripts that can recreate the entire directory structure:
#   - restore_git_repos.sh (for Linux/macOS)
#   - restore_git_repos.bat (for Windows)
#
# FEATURES:
#   ✓ Captures both 'origin' and 'backup' remotes
#   ✓ Preserves directory structure
#   ✓ Preserves branch information
#   ✓ Cross-platform compatible
#   ✓ Idempotent (safe to run multiple times)
#
# USAGE:
#   ./generate_restore_script.sh
#
# OUTPUT FILES:
#   ~/restore_git_repos.sh  - Linux/macOS restoration script
#   ~/restore_git_repos.bat - Windows restoration script
#
# HOW TO USE GENERATED SCRIPTS:
#   On Linux/macOS:
#     1. Copy restore_git_repos.sh to target machine
#     2. chmod +x restore_git_repos.sh
#     3. ./restore_git_repos.sh
#
#   On Windows:
#     1. Copy restore_git_repos.bat to target machine
#     2. Double-click or run in Command Prompt
#
# REQUIREMENTS:
#   - git
#   - Access to all repository remotes (SSH keys configured)
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23
################################################################################


set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

OUTPUT_SCRIPT_SH="restore_git_repos.sh"
OUTPUT_SCRIPT_BAT="restore_git_repos.bat"

echo -e "${BLUE}Scanning for git repositories with remotes under 'code' directory...${NC}\n"

# Start creating the bash restoration script
cat > "$OUTPUT_SCRIPT_SH" << 'HEADER'
#!/bin/bash

# Git repositories restoration script for Linux/macOS
# Generated automatically - restores all git repos with remotes
# Date: 2026-03-23

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Starting git repositories restoration...${NC}\n"

# Create base code directory if it doesn't exist
mkdir -p code
cd code

HEADER

# Start creating the Windows batch restoration script
cat > "$OUTPUT_SCRIPT_BAT" << 'HEADER'
@echo off
REM Git repositories restoration script for Windows
REM Generated automatically - restores all git repos with remotes
REM Date: 2026-03-23

echo Starting git repositories restoration...
echo.

REM Create base code directory if it doesn't exist
if not exist code mkdir code
cd code

HEADER

# Counter for repositories found
repo_count=0

# Get the absolute path of the code directory
CODE_DIR=$(cd code && pwd)

# Find all git repositories under the code directory
while IFS= read -r git_dir; do
    repo_path=$(dirname "$git_dir")
    
    cd "$repo_path" || continue
    
    # Get both origin and backup remote URLs
    origin_url=$(git remote get-url origin 2>/dev/null || echo "")
    backup_url=$(git remote get-url backup 2>/dev/null || echo "")
    
    # Skip repos without any remotes
    if [ -z "$origin_url" ] && [ -z "$backup_url" ]; then
        echo -e "${YELLOW}Skipping: ${repo_path} (no remote)${NC}"
        continue
    fi
    
    # Determine primary clone URL (prefer origin, fallback to backup)
    if [ -n "$origin_url" ]; then
        clone_url="$origin_url"
    else
        clone_url="$backup_url"
    fi
    
    # Get the absolute path and calculate relative path from code directory
    abs_repo_path=$(pwd)
    relative_path="${abs_repo_path#$CODE_DIR/}"
    
    # If the path is the same, it means we're at the code root
    if [ "$relative_path" = "$abs_repo_path" ]; then
        relative_path="."
    fi
    
    # Get the current branch
    current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
    
    echo -e "${GREEN}Found: ${relative_path}${NC}"
    echo -e "  Origin: ${origin_url:-none}"
    if [ -n "$backup_url" ]; then
        echo -e "  Backup: ${backup_url}"
    fi
    echo -e "  Branch: ${current_branch}"
    
    # Add to bash restoration script
    cat >> "$OUTPUT_SCRIPT_SH" << EOF

# Repository: ${relative_path}
echo -e "\${BLUE}Restoring: ${relative_path}\${NC}"
if [ -d "${relative_path}/.git" ]; then
    echo -e "  \${YELLOW}Directory already exists, skipping...\${NC}"
else
    # Create parent directory if needed
    mkdir -p "$(dirname "${relative_path}")"
    
    # Clone the repository
    if git clone "${clone_url}" "${relative_path}"; then
        echo -e "  \${GREEN}✓\${NC} Successfully cloned"
        
        # Checkout the original branch if not already on it
        cd "${relative_path}"
        current=\$(git rev-parse --abbrev-ref HEAD)
        if [ "\$current" != "${current_branch}" ]; then
            if git checkout "${current_branch}" 2>/dev/null; then
                echo -e "  \${GREEN}✓\${NC} Checked out branch: ${current_branch}"
            else
                echo -e "  \${YELLOW}⚠\${NC} Could not checkout branch: ${current_branch}"
            fi
        fi
EOF

    # Add backup remote if it exists and is different from origin
    if [ -n "$backup_url" ] && [ -n "$origin_url" ] && [ "$backup_url" != "$origin_url" ]; then
        cat >> "$OUTPUT_SCRIPT_SH" << EOF
        
        # Add backup remote
        if git remote add backup "${backup_url}" 2>/dev/null; then
            echo -e "  \${GREEN}✓\${NC} Added backup remote"
        fi
EOF
    fi

    cat >> "$OUTPUT_SCRIPT_SH" << EOF
        cd - > /dev/null
    else
        echo -e "  \${RED}✗\${NC} Failed to clone"
    fi
fi

EOF

    # Convert path separators for Windows
    windows_path="${relative_path//\//\\}"
    parent_dir=$(dirname "${relative_path}")
    windows_parent="${parent_dir//\//\\}"
    
    # Add to Windows batch restoration script
    cat >> "$OUTPUT_SCRIPT_BAT" << EOF

REM Repository: ${relative_path}
echo Restoring: ${relative_path}
if exist "${windows_path}\\.git" (
    echo   Directory already exists, skipping...
) else (
    REM Create parent directory if needed
    if not exist "${windows_parent}" mkdir "${windows_parent}"
    
    REM Clone the repository
    git clone "${clone_url}" "${windows_path}"
    if errorlevel 1 (
        echo   Failed to clone
    ) else (
        echo   Successfully cloned
        
        REM Checkout the original branch if not already on it
        cd "${windows_path}"
        git checkout "${current_branch}" 2>nul
        if errorlevel 1 (
            echo   Could not checkout branch: ${current_branch}
        ) else (
            echo   Checked out branch: ${current_branch}
        )
EOF

    # Add backup remote if it exists and is different from origin
    if [ -n "$backup_url" ] && [ -n "$origin_url" ] && [ "$backup_url" != "$origin_url" ]; then
        cat >> "$OUTPUT_SCRIPT_BAT" << EOF
        
        REM Add backup remote
        git remote add backup "${backup_url}" 2>nul
        if not errorlevel 1 (
            echo   Added backup remote
        )
EOF
    fi

    cat >> "$OUTPUT_SCRIPT_BAT" << EOF
        cd ..\\..
    )
)
echo.

EOF
    
    ((repo_count++))
    
done < <(find "$CODE_DIR" -type d -name ".git" 2>/dev/null)

# Add footer to bash restoration script
cat >> "$OUTPUT_SCRIPT_SH" << 'FOOTER'

echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Restoration completed!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
FOOTER

# Add footer to Windows batch restoration script
cat >> "$OUTPUT_SCRIPT_BAT" << 'FOOTER'

echo.
echo ===============================================================
echo Restoration completed!
echo ===============================================================
pause
FOOTER

# Make the bash restoration script executable
chmod +x "$OUTPUT_SCRIPT_SH"

# Print summary
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Restoration scripts generated!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "\nFound ${GREEN}${repo_count}${NC} repositories with remotes\n"
echo -e "Generated files:"
echo -e "  ${YELLOW}${OUTPUT_SCRIPT_SH}${NC} - For Linux/macOS"
echo -e "  ${YELLOW}${OUTPUT_SCRIPT_BAT}${NC} - For Windows"
echo -e "\nTo restore on Linux/macOS:"
echo -e "  1. Copy ${YELLOW}${OUTPUT_SCRIPT_SH}${NC} to the target machine"
echo -e "  2. Run: ${YELLOW}chmod +x ${OUTPUT_SCRIPT_SH}${NC}"
echo -e "  3. Run: ${YELLOW}./${OUTPUT_SCRIPT_SH}${NC}"
echo -e "\nTo restore on Windows:"
echo -e "  1. Copy ${YELLOW}${OUTPUT_SCRIPT_BAT}${NC} to the target machine"
echo -e "  2. Double-click ${YELLOW}${OUTPUT_SCRIPT_BAT}${NC} or run in Command Prompt"
echo -e "\nBoth scripts will recreate the directory structure and clone all repositories.\n"
