# restore.ps1
# 
# Complete system restoration script for Windows
#
# DESCRIPTION:
#   Restores a complete backup created by backup.sh on macOS. Performs restoration
#   in the optimal order: SSH keys first, then folders, then git repositories,
#   and finally non-git code folders and packages.
#
# FEATURES:
#   ✓ Restores SSH keys first (needed for git operations)
#   ✓ Restores all folders except code
#   ✓ Restores git repositories using generated restore script
#   ✓ Restores non-git folders from code directory
#   ✓ Installs packages using winget
#   ✓ Progress tracking and logging
#   ✓ Safety checks and confirmations
#
# USAGE:
#   .\restore.ps1 -BackupPath <path>
#
# EXAMPLES:
#   # From USB drive
#   .\restore.ps1 -BackupPath "D:\MacBackup"
#
#   # From network location
#   .\restore.ps1 -BackupPath "\\NAS\backups\MacBackup"
#
# RESTORATION ORDER:
#   1. SSH keys (~/.ssh → $HOME\.ssh)
#   2. Configuration folders
#   3. Git repositories (using restore_git_repos.bat)
#   4. Non-git code folders
#   5. Windows packages (using winget)
#
# REQUIREMENTS:
#   - PowerShell 5.1 or later
#   - Git for Windows
#   - GitHub CLI (gh) - will be installed if not present
#   - winget (Windows Package Manager)
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23

param(
    [Parameter(Mandatory=$true, HelpMessage="Path to the backup directory")]
    [string]$BackupPath
)

# Requires elevation
#Requires -RunAsAdministrator

# Start timing
$StartTime = Get-Date

# Setup logging
$LogFile = "$env:USERPROFILE\restore_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

function Write-Log {
    param([string]$Message, [string]$Color = "White")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host $Message -ForegroundColor $Color
    Add-Content -Path $LogFile -Value "[$timestamp] $Message"
}

function Write-Header {
    param([string]$Title)
    Write-Log ""
    Write-Log "===============================================================" -Color Cyan
    Write-Log $Title -Color Cyan
    Write-Log "===============================================================" -Color Cyan
    Write-Log ""
}

# Verify backup directory exists
if (-not (Test-Path $BackupPath)) {
    Write-Log "Error: Backup directory not found: $BackupPath" -Color Red
    exit 1
}

# Banner
Write-Header "SYSTEM RESTORATION FROM BACKUP"
Write-Log "Backup source: $BackupPath" -Color Blue
Write-Log "Log file: $LogFile" -Color Blue
Write-Log ""

# Verify backup contents
Write-Log "Verifying backup contents..." -Color Yellow
$requiredItems = @(".ssh", "code")
$missingItems = @()

foreach ($item in $requiredItems) {
    if (-not (Test-Path (Join-Path $BackupPath $item))) {
        $missingItems += $item
    }
}

if ($missingItems.Count -gt 0) {
    Write-Log "Warning: The following items are missing from backup:" -Color Red
    foreach ($item in $missingItems) {
        Write-Log "  - $item" -Color Yellow
    }
    $continue = Read-Host "Continue anyway? (y/N)"
    if ($continue -ne 'y' -and $continue -ne 'Y') {
        Write-Log "Restoration cancelled by user" -Color Yellow
        exit 0
    }
}

# Show what will be restored
Write-Log ""
Write-Log "The following will be restored:" -Color Blue
Write-Log "  - SSH keys and configuration" -Color Green
Write-Log "  - Application configurations" -Color Green
Write-Log "  - Git repositories" -Color Green
Write-Log "  - Non-git code folders" -Color Green
Write-Log "  - Windows packages (using winget)" -Color Green
Write-Log ""

# Confirmation
$confirm = Read-Host "Start restoration? This will overwrite existing files. Continue? (y/N)"
if ($confirm -ne 'y' -and $confirm -ne 'Y') {
    Write-Log "Restoration cancelled by user" -Color Yellow
    exit 0
}

Write-Log ""
Write-Log "Starting restoration..." -Color Green
Write-Log ""

################################################################################
# STEP 1: Restore SSH Keys
################################################################################
Write-Header "Step 1: Restoring SSH Keys"

$sshBackup = Join-Path $BackupPath ".ssh"
$sshTarget = Join-Path $env:USERPROFILE ".ssh"

if (Test-Path $sshBackup) {
    # Backup existing SSH keys if they exist
    if (Test-Path $sshTarget) {
        Write-Log "Backing up existing SSH keys..." -Color Yellow
        $backupTimestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $sshBackupTarget = "$sshTarget.backup_$backupTimestamp"
        Move-Item -Path $sshTarget -Destination $sshBackupTarget -Force
        Write-Log "Existing SSH keys backed up to: $sshBackupTarget" -Color Green
    }
    
    Write-Log "Restoring SSH keys..." -Color Blue
    Copy-Item -Path $sshBackup -Destination $sshTarget -Recurse -Force
    Write-Log "SSH keys restored" -Color Green
    
    # Test SSH connection
    Write-Log "Testing GitHub SSH connection..." -Color Blue
    $sshTest = ssh -T git@github.com 2>&1
    if ($sshTest -match "successfully authenticated") {
        Write-Log "GitHub SSH connection successful" -Color Green
    } else {
        Write-Log "GitHub SSH connection test failed (this is OK if keys need passphrase)" -Color Yellow
    }
} else {
    Write-Log "SSH backup not found, skipping" -Color Yellow
}

################################################################################
# STEP 2: Restore Configuration Folders
################################################################################
Write-Header "Step 2: Restoring Configuration Folders"

$foldersToRestore = @(
    ".config",
    "bin",
    "Desktop",
    "Downloads",
    "code_backup"  # Temporary, will sort out git vs non-git later
)

foreach ($folder in $foldersToRestore) {
    $sourcePath = Join-Path $BackupPath $folder
    $targetPath = Join-Path $env:USERPROFILE $folder
    
    if (Test-Path $sourcePath) {
        Write-Log "Restoring: $folder" -Color Blue
        
        # Create parent directory if needed
        $parentDir = Split-Path -Parent $targetPath
        if (-not (Test-Path $parentDir)) {
            New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
        }
        
        # Restore folder
        robocopy $sourcePath $targetPath /E /Z /R:3 /W:5 /MT:8 /LOG+:$LogFile | Out-Null
        Write-Log "Restored: $folder" -Color Green
    } else {
        Write-Log "Not found in backup: $folder" -Color Yellow
    }
}

################################################################################
# STEP 3: Install Git and GitHub CLI
################################################################################
Write-Header "Step 3: Installing Required Tools"

# Check for winget
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Log "winget not found. Please install it from Microsoft Store:" -Color Red
    Write-Log "https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1" -Color Yellow
    Write-Log "After installing, re-run this script" -Color Yellow
    exit 1
}

# Install Git if not present
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Log "Installing Git for Windows..." -Color Yellow
    winget install --id Git.Git -e --source winget --silent --accept-package-agreements --accept-source-agreements
    Write-Log "Git installed" -Color Green
    
    # Refresh PATH
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
} else {
    Write-Log "Git already installed" -Color Green
}

# Install GitHub CLI if not present
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Log "Installing GitHub CLI..." -Color Yellow
    winget install --id GitHub.cli -e --source winget --silent --accept-package-agreements --accept-source-agreements
    Write-Log "GitHub CLI installed" -Color Green
    
    # Refresh PATH
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
} else {
    Write-Log "GitHub CLI already installed" -Color Green
}

################################################################################
# STEP 4: Restore Git Repositories
################################################################################
Write-Header "Step 4: Restoring Git Repositories"

# Check if restore script exists
$restoreScript = Join-Path $env:USERPROFILE "restore_git_repos.bat"
$scriptsBackup = Join-Path $BackupPath "git_management_scripts\restore_git_repos.bat"

if (Test-Path $scriptsBackup) {
    Copy-Item -Path $scriptsBackup -Destination $restoreScript -Force
    Write-Log "Found restore script in backup" -Color Green
} elseif (-not (Test-Path $restoreScript)) {
    Write-Log "restore_git_repos.bat not found" -Color Yellow
    Write-Log "You'll need to generate it manually on the source machine" -Color Yellow
}

if (Test-Path $restoreScript) {
    Write-Log "Running git restore script..." -Color Blue
    
    # Create code directory
    $codeDir = Join-Path $env:USERPROFILE "code"
    New-Item -ItemType Directory -Path $codeDir -Force | Out-Null
    
    # Run the restore script
    Push-Location $codeDir
    & cmd /c $restoreScript *>> $LogFile
    Pop-Location
    
    Write-Log "Git repositories restored" -Color Green
} else {
    Write-Log "Skipping git restore (no restore script found)" -Color Yellow
}

################################################################################
# STEP 5: Restore Non-Git Code Folders
################################################################################
Write-Header "Step 5: Restoring Non-Git Code Folders"

$codeBackup = Join-Path $BackupPath "code"

if (Test-Path $codeBackup) {
    Write-Log "Checking for non-git folders in code backup..." -Color Blue
    
    $nonGitFolders = Get-ChildItem -Path $codeBackup -Directory | Where-Object {
        -not (Test-Path (Join-Path $_.FullName ".git"))
    }
    
    if ($nonGitFolders.Count -gt 0) {
        Write-Log "Found $($nonGitFolders.Count) non-git folder(s) to restore:" -Color Blue
        foreach ($folder in $nonGitFolders) {
            Write-Log "  - $($folder.Name)" -Color White
            $targetPath = Join-Path $env:USERPROFILE "code\$($folder.Name)"
            robocopy $folder.FullName $targetPath /E /Z /R:3 /W:5 /MT:8 /LOG+:$LogFile | Out-Null
            Write-Log "Restored: $($folder.Name)" -Color Green
        }
    } else {
        Write-Log "No non-git folders found (all code is in git)" -Color Green
    }
} else {
    Write-Log "Code backup directory not found" -Color Yellow
}

################################################################################
# STEP 6: Install Windows Packages
################################################################################
Write-Header "Step 6: Installing Windows Packages"

# Common development tools
$packagesToInstall = @(
    "Microsoft.PowerShell",
    "Microsoft.WindowsTerminal",
    "Microsoft.VisualStudioCode",
    "Python.Python.3.12",
    "OpenJS.NodeJS",
    "Neovim.Neovim",
    "GitHub.GitHubDesktop",
    "JanDeDobbeleer.OhMyPosh"
)

Write-Log "Installing common development packages..." -Color Blue
foreach ($package in $packagesToInstall) {
    try {
        Write-Log "Installing: $package" -Color Yellow
        winget install --id $package -e --source winget --silent --accept-package-agreements --accept-source-agreements *>> $LogFile
        Write-Log "Installed: $package" -Color Green
    } catch {
        Write-Log "Failed to install: $package" -Color Yellow
    }
}

################################################################################
# COMPLETION
################################################################################
Write-Header "Restoration Complete!"

# Calculate elapsed time
$endTime = Get-Date
$elapsed = $endTime - $StartTime
$hours = [math]::Floor($elapsed.TotalHours)
$minutes = $elapsed.Minutes
$seconds = $elapsed.Seconds

Write-Log ""
Write-Log "Summary:" -Color Blue
Write-Log "  ✓ SSH keys restored" -Color Green
Write-Log "  ✓ Configuration folders restored" -Color Green
Write-Log "  ✓ Git repositories restored" -Color Green
Write-Log "  ✓ Non-git folders restored" -Color Green
Write-Log "  ✓ Packages installed" -Color Green
Write-Log ""
Write-Log "Time taken:" -Color Blue
if ($hours -gt 0) {
    Write-Log "  ⏱ $($hours.ToString('00')):$($minutes.ToString('00')):$($seconds.ToString('00')) (HH:MM:SS)" -Color White
} else {
    Write-Log "  ⏱ $($minutes.ToString('00')):$($seconds.ToString('00')) (MM:SS)" -Color White
}
Write-Log ""
Write-Log "Log file: $LogFile" -Color Blue
Write-Log ""

Write-Log "Post-Restoration Steps:" -Color Yellow
Write-Log "  1. Authenticate with GitHub CLI:" -Color White
Write-Log "     gh auth login" -Color Cyan
Write-Log ""
Write-Log "  2. Verify SSH connection to GitHub:" -Color White
Write-Log "     ssh -T git@github.com" -Color Cyan
Write-Log ""
Write-Log "  3. Configure git user (if needed):" -Color White
Write-Log "     git config --global user.name `"Your Name`"" -Color Cyan
Write-Log "     git config --global user.email `"your@email.com`"" -Color Cyan
Write-Log ""
Write-Log "  4. Review and update any application configurations" -Color White
Write-Log ""
Write-Log "  5. Restart your computer to ensure all changes take effect" -Color White
Write-Log ""

Write-Log "Welcome back! Your system has been restored." -Color Green
Write-Log ""

# Prompt to view log
$viewLog = Read-Host "View log file? (y/N)"
if ($viewLog -eq 'y' -or $viewLog -eq 'Y') {
    notepad $LogFile
}
