#!/bin/bash

################################################################################
# restore.sh
# 
# Complete system restoration script for macOS/Linux
#
# DESCRIPTION:
#   Restores a complete backup created by backup.sh. Performs restoration in
#   the optimal order: SSH keys first (for git access), then folders, then
#   git repositories, and finally non-git code folders and packages.
#
# FEATURES:
#   ✓ Restores SSH keys first (needed for git operations)
#   ✓ Restores all folders except code
#   ✓ Restores git repositories using generated restore script
#   ✓ Restores non-git folders from code directory
#   ✓ Installs all Homebrew packages from Brewfile
#   ✓ Progress tracking and logging
#   ✓ Safety checks and confirmations
#
# USAGE:
#   ./restore.sh <backup_directory>
#
# ARGUMENTS:
#   backup_directory - Path to the MacBackup directory (usually ~/Documents/MacBackup)
#
# EXAMPLES:
#   # From iCloud backup
#   ./restore.sh ~/Documents/MacBackup
#
#   # From external drive
#   ./restore.sh /Volumes/Backup/MacBackup
#
#   # From network location
#   ./restore.sh /mnt/nas/backups/MacBackup
#
# RESTORATION ORDER:
#   1. SSH keys (~/.ssh)
#   2. Configuration folders (~/.config, etc.)
#   3. Git repositories (using restore_git_repos.sh)
#   4. Non-git code folders
#   5. Homebrew packages (Brewfile)
#
# REQUIREMENTS:
#   - rsync
#   - git
#   - gh (GitHub CLI) - will be installed if not present
#   - brew (Homebrew) - will be installed if not present
#
# SAFETY:
#   - Asks for confirmation before starting
#   - Backs up existing files before overwriting
#   - Creates detailed log file
#   - Never deletes without confirmation
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23
################################################################################

set -e

# Record start time
START_TIME=$(date +%s)

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Log file
LOG_FILE="$HOME/restore_$(date +%Y%m%d_%H%M%S).log"

# Logging function
log() {
    echo -e "$1" | tee -a "$LOG_FILE"
}

log_no_color() {
    echo "$1" >> "$LOG_FILE"
}

# Show usage
if [ $# -eq 0 ]; then
    echo -e "${RED}Error: Backup directory not specified${NC}"
    echo ""
    echo "Usage: $0 <backup_directory>"
    echo ""
    echo "Examples:"
    echo "  $0 ~/Documents/MacBackup"
    echo "  $0 /Volumes/Backup/MacBackup"
    echo ""
    exit 1
fi

BACKUP_DIR="$1"

# Verify backup directory exists
if [ ! -d "$BACKUP_DIR" ]; then
    echo -e "${RED}Error: Backup directory not found: $BACKUP_DIR${NC}"
    exit 1
fi

# Banner
echo ""
log "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
log "${CYAN}           SYSTEM RESTORATION FROM BACKUP                       ${NC}"
log "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
log "${BLUE}Backup source:${NC} $BACKUP_DIR"
log "${BLUE}Log file:${NC} $LOG_FILE"
echo ""

# Verify backup contents
log "${YELLOW}Verifying backup contents...${NC}"
required_items=(".ssh" "code")
missing_items=()

for item in "${required_items[@]}"; do
    if [ ! -d "$BACKUP_DIR/$item" ]; then
        missing_items+=("$item")
    fi
done

if [ ${#missing_items[@]} -gt 0 ]; then
    log "${RED}Warning: The following items are missing from backup:${NC}"
    for item in "${missing_items[@]}"; do
        log "  - $item"
    done
    echo ""
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log "${YELLOW}Restoration cancelled by user${NC}"
        exit 0
    fi
fi

# Show what will be restored
echo ""
log "${BLUE}The following will be restored:${NC}"
log "${GREEN}├─${NC} SSH keys and configuration"
log "${GREEN}├─${NC} Application configurations"
log "${GREEN}├─${NC} Git repositories"
log "${GREEN}├─${NC} Non-git code folders"
log "${GREEN}└─${NC} Homebrew packages (if Brewfile exists)"
echo ""

# Confirmation
read -p "$(echo -e ${YELLOW}Start restoration? This will overwrite existing files. Continue? '(y/N): '${NC})" -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log "${YELLOW}Restoration cancelled by user${NC}"
    exit 0
fi

echo ""
log "${GREEN}Starting restoration...${NC}"
echo ""

################################################################################
# STEP 1: Restore SSH Keys
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 1: Restoring SSH Keys${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

if [ -d "$BACKUP_DIR/.ssh" ]; then
    # Backup existing SSH keys if they exist
    if [ -d "$HOME/.ssh" ]; then
        log "${YELLOW}Backing up existing SSH keys...${NC}"
        BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        mv "$HOME/.ssh" "$HOME/.ssh.backup_$BACKUP_TIMESTAMP"
        log "${GREEN}✓${NC} Existing SSH keys backed up to: $HOME/.ssh.backup_$BACKUP_TIMESTAMP"
    fi
    
    log "${BLUE}Restoring SSH keys...${NC}"
    rsync -avh --progress "$BACKUP_DIR/.ssh/" "$HOME/.ssh/" >> "$LOG_FILE" 2>&1
    
    # Fix permissions (critical for SSH)
    chmod 700 "$HOME/.ssh"
    chmod 600 "$HOME/.ssh/"* 2>/dev/null || true
    chmod 644 "$HOME/.ssh/"*.pub 2>/dev/null || true
    chmod 644 "$HOME/.ssh/config" 2>/dev/null || true
    chmod 644 "$HOME/.ssh/known_hosts" 2>/dev/null || true
    
    log "${GREEN}✓${NC} SSH keys restored and permissions set"
    
    # Test SSH connection
    log "${BLUE}Testing GitHub SSH connection...${NC}"
    if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
        log "${GREEN}✓${NC} GitHub SSH connection successful"
    else
        log "${YELLOW}⚠${NC} GitHub SSH connection test failed (this is OK if keys need passphrase)"
    fi
else
    log "${YELLOW}⚠${NC} SSH backup not found, skipping"
fi

echo ""

################################################################################
# STEP 2: Restore Configuration Folders
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 2: Restoring Configuration Folders${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# List of folders to restore (excluding .ssh and code which are handled separately)
FOLDERS_TO_RESTORE=(
    ".config"
    ".copilot"
    "bin"
    "Desktop"
    "Downloads"
    "koshodojo"
    "negmas"
    ".secrets"
)

for folder in "${FOLDERS_TO_RESTORE[@]}"; do
    if [ -d "$BACKUP_DIR/$folder" ]; then
        log "${BLUE}Restoring:${NC} $folder"
        
        # Create parent directory if needed
        parent_dir=$(dirname "$HOME/$folder")
        mkdir -p "$parent_dir"
        
        # Restore folder
        rsync -avh --progress "$BACKUP_DIR/$folder/" "$HOME/$folder/" >> "$LOG_FILE" 2>&1
        log "${GREEN}✓${NC} Restored: $folder"
    else
        log "${YELLOW}⚠${NC} Not found in backup: $folder"
    fi
done

echo ""

################################################################################
# STEP 3: Install Homebrew (if not installed)
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 3: Installing Homebrew (if needed)${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

if ! command -v brew &> /dev/null; then
    log "${YELLOW}Homebrew not found, installing...${NC}"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    # Add to PATH for this session
    if [[ $(uname -m) == "arm64" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        eval "$(/usr/local/bin/brew shellenv)"
    fi
    
    log "${GREEN}✓${NC} Homebrew installed"
else
    log "${GREEN}✓${NC} Homebrew already installed"
fi

# Install GitHub CLI if not present
if ! command -v gh &> /dev/null; then
    log "${YELLOW}Installing GitHub CLI...${NC}"
    brew install gh
    log "${GREEN}✓${NC} GitHub CLI installed"
else
    log "${GREEN}✓${NC} GitHub CLI already installed"
fi

echo ""

################################################################################
# STEP 4: Restore Git Repositories
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 4: Restoring Git Repositories${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check if restore script exists
RESTORE_SCRIPT="$HOME/restore_git_repos.sh"

# Check in backup scripts directory first
if [ -f "$BACKUP_DIR/git_management_scripts/restore_git_repos.sh" ]; then
    cp "$BACKUP_DIR/git_management_scripts/restore_git_repos.sh" "$RESTORE_SCRIPT"
    log "${GREEN}✓${NC} Found restore script in backup"
elif [ ! -f "$RESTORE_SCRIPT" ]; then
    log "${YELLOW}⚠${NC} restore_git_repos.sh not found"
    log "${YELLOW}You'll need to run generate_restore_script.sh manually${NC}"
else
    log "${GREEN}✓${NC} Using existing restore script"
fi

if [ -f "$RESTORE_SCRIPT" ]; then
    log "${BLUE}Running git restore script...${NC}"
    chmod +x "$RESTORE_SCRIPT"
    
    # Create code directory
    mkdir -p "$HOME/code"
    cd "$HOME/code"
    
    # Run the restore script
    if "$RESTORE_SCRIPT" >> "$LOG_FILE" 2>&1; then
        log "${GREEN}✓${NC} Git repositories restored"
    else
        log "${YELLOW}⚠${NC} Some repositories may have failed to restore (check log)"
    fi
else
    log "${YELLOW}⚠${NC} Skipping git restore (no restore script found)"
fi

echo ""

################################################################################
# STEP 5: Restore Non-Git Code Folders
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 5: Restoring Non-Git Code Folders${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

if [ -d "$BACKUP_DIR/code" ]; then
    log "${BLUE}Checking for non-git folders in code backup...${NC}"
    
    # Find all directories in backup/code that don't have .git
    non_git_folders=()
    while IFS= read -r -d '' folder; do
        folder_name=$(basename "$folder")
        if [ ! -d "$folder/.git" ]; then
            non_git_folders+=("$folder_name")
        fi
    done < <(find "$BACKUP_DIR/code" -mindepth 1 -maxdepth 1 -type d -print0)
    
    if [ ${#non_git_folders[@]} -gt 0 ]; then
        log "${BLUE}Found ${#non_git_folders[@]} non-git folder(s) to restore:${NC}"
        for folder in "${non_git_folders[@]}"; do
            log "  - $folder"
            rsync -avh --progress "$BACKUP_DIR/code/$folder/" "$HOME/code/$folder/" >> "$LOG_FILE" 2>&1
            log "${GREEN}✓${NC} Restored: $folder"
        done
    else
        log "${GREEN}✓${NC} No non-git folders found (all code is in git)"
    fi
else
    log "${YELLOW}⚠${NC} Code backup directory not found"
fi

echo ""

################################################################################
# STEP 6: Install Packages from Brewfile
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${BLUE}Step 6: Installing Packages from Brewfile${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check for Brewfile in multiple locations
BREWFILE=""
if [ -f "$HOME/code/personal/dotfiles/Brewfile" ]; then
    BREWFILE="$HOME/code/personal/dotfiles/Brewfile"
elif [ -f "$BACKUP_DIR/code/personal/dotfiles/Brewfile" ]; then
    BREWFILE="$BACKUP_DIR/code/personal/dotfiles/Brewfile"
elif [ -f "$HOME/Brewfile" ]; then
    BREWFILE="$HOME/Brewfile"
fi

if [ -n "$BREWFILE" ]; then
    log "${BLUE}Found Brewfile:${NC} $BREWFILE"
    log "${BLUE}Installing packages (this may take a while)...${NC}"
    echo ""
    
    if brew bundle install --file="$BREWFILE" >> "$LOG_FILE" 2>&1; then
        log "${GREEN}✓${NC} Packages installed successfully"
    else
        log "${YELLOW}⚠${NC} Some packages may have failed to install (check log)"
    fi
else
    log "${YELLOW}⚠${NC} Brewfile not found, skipping package installation"
    log "${BLUE}ⓘ${NC} You can install packages later with: brew bundle install"
fi

echo ""

################################################################################
# COMPLETION
################################################################################
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
log "${GREEN}Restoration Complete!${NC}"
log "${BLUE}═══════════════════════════════════════════════════════════════${NC}"

# Calculate elapsed time
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))
HOURS=$((ELAPSED / 3600))
MINUTES=$(((ELAPSED % 3600) / 60))
SECONDS=$((ELAPSED % 60))

echo ""
log "${BLUE}Summary:${NC}"
log "  ${GREEN}✓${NC} SSH keys restored"
log "  ${GREEN}✓${NC} Configuration folders restored"
log "  ${GREEN}✓${NC} Git repositories restored"
log "  ${GREEN}✓${NC} Non-git folders restored"
log "  ${GREEN}✓${NC} Packages installed"
echo ""
log "${BLUE}Time taken:${NC}"
if [ $HOURS -gt 0 ]; then
    log "  ⏱  $(printf '%02d:%02d:%02d' $HOURS $MINUTES $SECONDS) (HH:MM:SS)"
else
    log "  ⏱  $(printf '%02d:%02d' $MINUTES $SECONDS) (MM:SS)"
fi
echo ""
log "${BLUE}Log file:${NC} $LOG_FILE"
echo ""

log "${YELLOW}Post-Restoration Steps:${NC}"
log "  1. Authenticate with GitHub CLI:"
log "     ${CYAN}gh auth login${NC}"
log ""
log "  2. Verify SSH connection to GitHub:"
log "     ${CYAN}ssh -T git@github.com${NC}"
log ""
log "  3. Configure git user (if needed):"
log "     ${CYAN}git config --global user.name \"Your Name\"${NC}"
log "     ${CYAN}git config --global user.email \"your@email.com\"${NC}"
log ""
log "  4. Review and update any application configurations"
log ""
log "  5. Reboot your system to ensure all changes take effect"
echo ""

log "${GREEN}Welcome back! Your system has been restored.${NC}"
echo ""
