#!/bin/bash

################################################################################
# update_git_repos.sh
# 
# Comprehensive git repository backup and management script
#
# DESCRIPTION:
#   Recursively scans ~/code for git repositories and performs the following:
#   - Auto-commits uncommitted changes with WIP message
#   - Converts HTTPS URLs to SSH
#   - Migrates Bitbucket/GitLab repos to GitHub
#   - Creates GitHub repos for local-only repos
#   - Pushes changes to owned GitHub repos
#   - Creates backup repos for external/diverged repos
#   - Respects ignore list in ~/.git_repos_ignore
#
# FEATURES:
#   ✓ Fully unattended operation (never prompts for input)
#   ✓ Rate limiting (max 50 GitHub repos per run, 3s delay)
#   ✓ Ownership checking (only pushes to your repos)
#   ✓ SSH-only (converts all HTTPS to SSH)
#   ✓ Comprehensive error handling and reporting
#   ✓ Timeout protection (30s per push operation)
#
# REPOSITORY HANDLING:
#   1. No remote: Creates GitHub repo, sets as origin, pushes
#   2. HTTPS URLs: Converts to SSH automatically
#   3. Bitbucket/GitLab: Migrates to GitHub (replaces origin)
#   4. Owned repos: Pushes to origin
#   5. External repos: Creates backup repo with -backup suffix
#   6. Diverged repos: Creates fork repo with -fork suffix
#   7. Ignored repos: Skipped completely
#
# USAGE:
#   ./update_git_repos.sh
#
# CONFIGURATION:
#   Edit MY_GITHUB_ACCOUNTS in this file (lines 50-51)
#   Edit ~/.git_repos_ignore to skip specific repos
#
# REQUIREMENTS:
#   - git
#   - gh (GitHub CLI) - Install: brew install gh
#   - SSH keys configured for GitHub
#   - timeout command (comes with coreutils)
#
# FILES USED:
#   ~/.git_repos_ignore - List of repos to skip (one per line)
#
# AUTHOR:
#   Generated by OpenCode
#   Date: 2026-03-23
################################################################################

# Prevent git from prompting for credentials (fail fast instead)
export GIT_TERMINAL_PROMPT=0
export GIT_SSH_COMMAND="ssh -o BatchMode=yes -o ConnectTimeout=5"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Arrays to store repository information
declare -a repos_no_remote=()
declare -a repos_behind_remote=()
declare -a repos_with_uncommitted=()
declare -a repos_pushed=()
declare -a repos_ignored=()
declare -a repos_https_converted=()
declare -a repos_bitbucket_mirrored=()
declare -a repos_diverged=()
declare -a repos_push_failed=()

# Counters
total_repos_found=0
total_repos_checked=0
github_repos_created=0

# Rate limiting for GitHub API
# GitHub recommends staying under 80 repo creations per hour
# We'll use 3 seconds between creations to be safe (max ~1200/hour, but batched)
GITHUB_API_DELAY=3  # seconds between GitHub repo creations
MAX_GITHUB_REPOS_PER_RUN=50  # Safety limit to prevent abuse

# My GitHub usernames/organizations
MY_GITHUB_ACCOUNTS=("yasserfarouk" "autoneg" "yassernec")

# Function to check if a remote URL belongs to my accounts
is_my_repo() {
    local url="$1"
    for account in "${MY_GITHUB_ACCOUNTS[@]}"; do
        if [[ "$url" =~ github\.com[:/]${account}/ ]]; then
            return 0  # Is my repo
        fi
    done
    return 1  # Not my repo
}

# Function to create GitHub repo with rate limiting
create_github_repo() {
    local repo_name="$1"
    local github_url=""
    
    # Check if we've hit the safety limit
    if [ $github_repos_created -ge $MAX_GITHUB_REPOS_PER_RUN ]; then
        echo -e "    ${RED}⚠${NC} GitHub repo creation limit reached ($MAX_GITHUB_REPOS_PER_RUN)"
        echo -e "    ${YELLOW}Run the script again later to create more repos${NC}"
        echo "|LIMIT_REACHED"
        return 1
    fi
    
    # Check if repo already exists
    if gh repo view "$repo_name" &>/dev/null; then
        github_url=$(gh repo view "$repo_name" --json sshUrl -q .sshUrl)
        echo "$github_url|EXISTS"
        return 0
    fi
    
    # Rate limit: sleep if we've created repos recently
    if [ $github_repos_created -gt 0 ]; then
        echo -e "    ${BLUE}⏱${NC} Rate limiting: waiting ${GITHUB_API_DELAY}s before creating repo..."
        sleep $GITHUB_API_DELAY
    fi
    
    # Create the repo
    if gh repo create "$repo_name" --private --source=. 2>/dev/null; then
        github_url=$(gh repo view "$repo_name" --json sshUrl -q .sshUrl 2>/dev/null)
        ((github_repos_created++))
        echo -e "    ${GREEN}✓${NC} Created repo ($github_repos_created/$MAX_GITHUB_REPOS_PER_RUN)"
        echo "$github_url|CREATED"
        return 0
    else
        echo -e "    ${RED}✗${NC} Failed to create GitHub repository"
        echo "|FAILED"
        return 1
    fi
}

# Load ignore list
IGNORE_FILE="$HOME/.git_repos_ignore"
declare -a ignore_patterns=()

if [ -f "$IGNORE_FILE" ]; then
    while IFS= read -r line; do
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        ignore_patterns+=("$line")
    done < "$IGNORE_FILE"
fi

echo -e "${BLUE}Scanning for git repositories under 'code' directory...${NC}\n"

# Define code directory
CODE_DIR="$HOME/code"

if [ ! -d "$CODE_DIR" ]; then
    echo -e "${RED}Error: Directory $CODE_DIR does not exist${NC}"
    exit 1
fi

# Function to check if repo should be ignored
should_ignore() {
    local repo_path="$1"
    local relative_path="${repo_path#$CODE_DIR/}"
    
    for pattern in "${ignore_patterns[@]}"; do
        if [[ "$relative_path" == "$pattern"* ]]; then
            return 0  # Should ignore
        fi
    done
    return 1  # Should not ignore
}

# Function to convert HTTPS URL to SSH
convert_https_to_ssh() {
    local url="$1"
    
    # Check if it's already SSH
    if [[ "$url" =~ ^git@ ]]; then
        echo "$url"
        return 0
    fi
    
    # Convert HTTPS to SSH
    if [[ "$url" =~ https://github\.com/([^/]+)/(.+)\.git ]]; then
        echo "git@github.com:${BASH_REMATCH[1]}/${BASH_REMATCH[2]}.git"
        return 0
    elif [[ "$url" =~ https://github\.com/([^/]+)/(.+) ]]; then
        echo "git@github.com:${BASH_REMATCH[1]}/${BASH_REMATCH[2]}.git"
        return 0
    fi
    
    # Return original if not GitHub or already converted
    echo "$url"
    return 1
}

# Find all git repositories under the code directory
while IFS= read -r git_dir; do
    repo_path=$(dirname "$git_dir")
    
    ((total_repos_found++))
    
    echo -e "${YELLOW}Processing: ${repo_path}${NC}"
    
    cd "$repo_path" || continue
    
    # Check if repo should be ignored
    if should_ignore "$repo_path"; then
        repos_ignored+=("$repo_path")
        echo -e "  ${BLUE}ⓘ${NC} Skipped (in ignore list)"
        continue
    fi
    
    ((total_repos_checked++))
    
    # Check if repo has a remote
    if ! git remote -v | grep -q '^origin'; then
        echo -e "  ${RED}✗${NC} No remote configured"
        
        # Extract repo name from path for GitHub repo name
        base_repo_name=$(basename "$repo_path")
        github_repo_name="$base_repo_name"
        
        echo -e "  ${BLUE}→${NC} Creating GitHub repository: $github_repo_name"
        
        # Use the rate-limited function to create repo
        result=$(create_github_repo "$github_repo_name")
        IFS='|' read -r github_url status <<< "$result"
        
        if [ "$status" == "EXISTS" ]; then
            echo -e "  ${YELLOW}⚠${NC} GitHub repo '$github_repo_name' already exists"
        elif [ "$status" == "LIMIT_REACHED" ]; then
            repos_no_remote+=("$repo_path|$github_repo_name|LIMIT_REACHED")
            echo ""
            continue
        elif [ "$status" == "FAILED" ]; then
            repos_no_remote+=("$repo_path|$github_repo_name|FAILED")
            echo ""
            continue
        fi
        
        if [ -n "$github_url" ]; then
            # Add origin remote
            git remote add origin "$github_url"
            echo -e "  ${GREEN}✓${NC} Added origin remote: $github_url"
            
            # Get current branch
            current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
            
            # Set upstream and push
            echo -e "  ${BLUE}→${NC} Pushing to GitHub..."
            if timeout 30 git push -u origin "$current_branch" &>/dev/null; then
                repos_no_remote+=("$repo_path|$github_repo_name|SUCCESS")
                echo -e "  ${GREEN}✓${NC} Successfully pushed to GitHub"
            else
                repos_no_remote+=("$repo_path|$github_repo_name|PUSH_FAILED")
                repos_push_failed+=("$repo_path|New repo without remote|$github_url")
                echo -e "  ${YELLOW}⚠${NC} Failed to push to GitHub (timeout or auth issue)"
            fi
        fi
        
        echo ""
        continue
    fi
    
    # Get remote URL and check if it needs conversion
    remote_url=$(git remote get-url origin 2>/dev/null || echo "")
    
    if [[ "$remote_url" =~ ^https:// ]]; then
        ssh_url=$(convert_https_to_ssh "$remote_url")
        if [ "$ssh_url" != "$remote_url" ]; then
            echo -e "  ${YELLOW}⚠${NC} Converting HTTPS to SSH..."
            if git remote set-url origin "$ssh_url" 2>/dev/null; then
                repos_https_converted+=("$repo_path|$remote_url|$ssh_url")
                echo -e "  ${GREEN}✓${NC} Converted to SSH: $ssh_url"
                remote_url="$ssh_url"
            else
                echo -e "  ${RED}✗${NC} Failed to convert URL"
            fi
        fi
    fi
    
    # Check if this is a Bitbucket or GitLab repository and migrate to GitHub
    if [[ "$remote_url" =~ bitbucket\.org ]] || [[ "$remote_url" =~ gitlab\.com ]]; then
        if [[ "$remote_url" =~ bitbucket\.org ]]; then
            service_name="Bitbucket"
            service_pattern="bitbucket\.org[:/]([^/]+)/([^/.]+)"
        else
            service_name="GitLab"
            service_pattern="gitlab\.com[:/]([^/]+)/([^/.]+)"
        fi
        
        echo -e "  ${BLUE}ⓘ${NC} $service_name repository detected - migrating to GitHub"
        
        # Extract repo name from URL
        if [[ "$remote_url" =~ $service_pattern ]]; then
            source_user="${BASH_REMATCH[1]}"
            repo_name="${BASH_REMATCH[2]}"
            repo_name="${repo_name%.git}"
            
            echo -e "  ${BLUE}→${NC} Creating GitHub repository: $repo_name"
            
            # Use rate-limited function to create GitHub repo
            result=$(create_github_repo "$repo_name")
            github_url="${result%|*}"
            status="${result#*|}"
            
            if [[ "$status" == "LIMIT_REACHED" ]]; then
                echo -e "  ${RED}⚠${NC} Skipping migration due to rate limit"
                continue
            fi
            
            if [ -n "$github_url" ]; then
                if [[ "$status" == "EXISTS" ]]; then
                    echo -e "  ${YELLOW}⚠${NC} GitHub repo already exists"
                fi
                
                # Remove old remote and replace with GitHub
                echo -e "  ${BLUE}→${NC} Replacing $service_name remote with GitHub..."
                git remote remove origin
                git remote add origin "$github_url"
                echo -e "  ${GREEN}✓${NC} Origin remote now points to GitHub"
                
                # Update remote_url for later use
                remote_url="$github_url"
                
                # Push all branches to GitHub
                echo -e "  ${BLUE}→${NC} Pushing all branches to GitHub..."
                if timeout 60 git push origin --all &>/dev/null && timeout 30 git push origin --tags &>/dev/null; then
                    repos_bitbucket_mirrored+=("$repo_path|$repo_name|$github_url|$service_name")
                    echo -e "  ${GREEN}✓${NC} Migrated to GitHub successfully"
                else
                    echo -e "  ${YELLOW}⚠${NC} Partial push to GitHub (timeout or auth issue)"
                fi
            else
                echo -e "  ${RED}✗${NC} Failed to create GitHub repository - skipping migration"
            fi
        fi
    fi
    
    # Get the current branch
    current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
    
    if [ "$current_branch" == "HEAD" ]; then
        echo -e "  ${YELLOW}⚠${NC} Detached HEAD state, skipping"
        continue
    fi
    
    # Check if the current branch has a tracking branch
    if ! git rev-parse --abbrev-ref --symbolic-full-name @{u} &>/dev/null; then
        echo -e "  ${YELLOW}⚠${NC} Branch '$current_branch' has no upstream tracking branch"
        continue
    fi
    
    # Fetch latest changes from remote
    echo -e "  Fetching from remote..."
    git fetch origin &>/dev/null || {
        echo -e "  ${RED}✗${NC} Failed to fetch from remote"
        continue
    }
    
    # Check for uncommitted changes and commit them
    has_uncommitted=false
    if ! git diff-index --quiet HEAD -- 2>/dev/null || [ -n "$(git ls-files --others --exclude-standard)" ]; then
        has_uncommitted=true
        echo -e "  ${YELLOW}⚠${NC} Has uncommitted changes"
        
        # Check if changes are only in submodules
        if git diff --name-only | grep -q '^' || git ls-files --others --exclude-standard | grep -q '^'; then
            echo -e "  ${BLUE}→${NC} Staging and committing changes..."
            
            # Stage all changes except submodules (modified, deleted, and new files)
            git add -A
            
            # Ensure git has user config (use global if not set locally)
            if ! git config user.email &>/dev/null; then
                git config user.email "backup@script.local"
                git config user.name "Backup Script"
            fi
            
            # Commit with WIP message
            if git commit -m "WIP: an intermediary commit for backup" &>/dev/null; then
                echo -e "  ${GREEN}✓${NC} Committed changes with WIP message"
                repos_with_uncommitted+=("$repo_path|$current_branch")
            else
                echo -e "  ${YELLOW}⚠${NC} Failed to commit changes (may be submodule-only changes)"
            fi
        else
            echo -e "  ${YELLOW}⚠${NC} Changes are submodule-only, skipping commit"
        fi
    fi
    
    # Get commit counts (recalculate after potential commit)
    upstream="@{u}"
    local_commits=$(git rev-list --count "$upstream..HEAD" 2>/dev/null || echo "0")
    remote_commits=$(git rev-list --count "HEAD..$upstream" 2>/dev/null || echo "0")
    
    # Check if remote is ahead
    if [ "$remote_commits" -gt 0 ]; then
        repos_behind_remote+=("$repo_path|$current_branch|$remote_commits")
        echo -e "  ${RED}↓${NC} Remote is ahead by $remote_commits commit(s)"
    fi
    
    # Check if local has commits not on remote and push them
    if [ "$local_commits" -gt 0 ]; then
        echo -e "  ${GREEN}↑${NC} Local has $local_commits commit(s) ahead of remote"
        
        # Check if history has diverged (both local and remote have commits)
        if [ "$remote_commits" -gt 0 ]; then
            echo -e "  ${YELLOW}⚠${NC} History has diverged - cannot push to original remote"
            
            # Extract repo name from path for GitHub repo name
            base_repo_name=$(basename "$repo_path")
            github_repo_name="${base_repo_name}-fork"
            
            echo -e "  ${BLUE}→${NC} Creating GitHub backup repository: $github_repo_name"
            
            # Use the rate-limited function to create repo
            result=$(create_github_repo "$github_repo_name")
            IFS='|' read -r github_url status <<< "$result"
            
            if [ "$status" == "EXISTS" ]; then
                echo -e "  ${YELLOW}⚠${NC} GitHub repo '$github_repo_name' already exists"
            elif [ "$status" == "LIMIT_REACHED" ]; then
                repos_diverged+=("$repo_path|$current_branch|$local_commits|$remote_commits|LIMIT_REACHED")
                echo ""
                continue
            fi
            
            if [ -n "$github_url" ]; then
                # Ensure we're using SSH URL
                if [[ "$github_url" =~ ^https:// ]]; then
                    github_url=$(convert_https_to_ssh "$github_url")
                fi
                
                # Check if 'backup' remote already exists
                if git remote get-url backup &>/dev/null; then
                    git remote set-url backup "$github_url"
                else
                    git remote add backup "$github_url"
                    echo -e "  ${GREEN}✓${NC} Added 'backup' remote"
                fi
                
                # Push to GitHub backup (with timeout to avoid hanging on auth prompts)
                echo -e "  ${BLUE}→${NC} Pushing to GitHub backup..."
                if timeout 30 git push backup "$current_branch" --force &>/dev/null; then
                    repos_diverged+=("$repo_path|$current_branch|$local_commits|$remote_commits|$github_repo_name")
                    echo -e "  ${GREEN}✓${NC} Pushed to GitHub backup: $github_repo_name"
                else
                    repos_push_failed+=("$repo_path|Diverged history fork|$github_url")
                    echo -e "  ${YELLOW}⚠${NC} Failed to push to GitHub backup (timeout or auth issue)"
                    repos_diverged+=("$repo_path|$current_branch|$local_commits|$remote_commits|PUSH_FAILED")
                fi
            else
                repos_diverged+=("$repo_path|$current_branch|$local_commits|$remote_commits|FAILED")
            fi
        else
            # Check if this is my repo before attempting to push
            if is_my_repo "$remote_url"; then
                echo -e "  Pushing to remote..."
                
                if timeout 30 git push origin "$current_branch" &>/dev/null; then
                    repos_pushed+=("$repo_path|$current_branch|$local_commits")
                    echo -e "  ${GREEN}✓${NC} Successfully pushed $local_commits commit(s)"
                else
                    repos_push_failed+=("$repo_path|Owned repo|$remote_url")
                    echo -e "  ${YELLOW}⚠${NC} Failed to push commits (timeout or auth issue)"
                fi
            else
                # Not my repo - create a backup on my GitHub
                echo -e "  ${BLUE}ⓘ${NC} External repository - creating backup on your GitHub"
                
                # Extract repo name from path for GitHub repo name
                base_repo_name=$(basename "$repo_path")
                github_repo_name="${base_repo_name}-backup"
                
                echo -e "  ${BLUE}→${NC} Creating GitHub backup repository: $github_repo_name"
                
                # Use the rate-limited function to create repo
                result=$(create_github_repo "$github_repo_name")
                IFS='|' read -r github_url status <<< "$result"
                
                if [ "$status" == "LIMIT_REACHED" ]; then
                    echo -e "  ${YELLOW}⚠${NC} Reached repo creation limit, will retry on next run"
                elif [ -n "$github_url" ]; then
                    # Ensure we're using SSH URL
                    if [[ "$github_url" =~ ^https:// ]]; then
                        github_url=$(convert_https_to_ssh "$github_url")
                    fi
                    
                    # Check if 'backup' remote already exists
                    if git remote get-url backup &>/dev/null; then
                        git remote set-url backup "$github_url"
                    else
                        git remote add backup "$github_url"
                        echo -e "  ${GREEN}✓${NC} Added 'backup' remote"
                    fi
                    
                    # Push to GitHub backup with timeout
                    echo -e "  ${BLUE}→${NC} Pushing to GitHub backup..."
                    if timeout 30 git push backup "$current_branch" &>/dev/null; then
                        echo -e "  ${GREEN}✓${NC} Pushed to GitHub backup: $github_repo_name"
                    else
                        repos_push_failed+=("$repo_path|External repo backup|$github_url")
                        echo -e "  ${YELLOW}⚠${NC} Failed to push to GitHub backup (timeout or auth issue)"
                    fi
                fi
            fi
        fi
    else
        if ! $has_uncommitted; then
            echo -e "  ${GREEN}✓${NC} Up to date with remote"
        fi
    fi
    
    echo ""
    
done < <(find "$CODE_DIR" -type d -name ".git" 2>/dev/null)

# Print summary reports
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}                     SUMMARY REPORT                             ${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}\n"

# Report 1: Repositories without remotes
if [ ${#repos_no_remote[@]} -gt 0 ]; then
    echo -e "${RED}Repositories Without Remotes:${NC}"
    echo "┌────────────────────────────────────────────────────────────────┐"
    printf "│ %-62s │\n" "Repository Path"
    echo "├────────────────────────────────────────────────────────────────┤"
    for repo in "${repos_no_remote[@]}"; do
        printf "│ %-62s │\n" "$repo"
    done
    echo "└────────────────────────────────────────────────────────────────┘"
    echo ""
else
    echo -e "${GREEN}✓ All repositories have remotes configured${NC}\n"
fi

# Report 2: Repositories behind remote
if [ ${#repos_behind_remote[@]} -gt 0 ]; then
    echo -e "${RED}Repositories Behind Remote:${NC}"
    echo "┌───────────────────────────────────────────┬──────────┬─────────┐"
    printf "│ %-41s │ %-8s │ %-7s │\n" "Repository Path" "Branch" "Behind"
    echo "├───────────────────────────────────────────┼──────────┼─────────┤"
    for entry in "${repos_behind_remote[@]}"; do
        IFS='|' read -r repo branch commits <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 41 ]; then
            repo="...${repo: -38}"
        fi
        if [ ${#branch} -gt 8 ]; then
            branch="${branch:0:7}…"
        fi
        printf "│ %-41s │ %-8s │ %7s │\n" "$repo" "$branch" "$commits"
    done
    echo "└───────────────────────────────────────────┴──────────┴─────────┘"
    echo ""
else
    echo -e "${GREEN}✓ No repositories are behind their remotes${NC}\n"
fi

# Report: Repositories with diverged history
if [ ${#repos_diverged[@]} -gt 0 ]; then
    echo -e "${YELLOW}Repositories With Diverged History (Not Pushed):${NC}"
    echo "┌──────────────────────────────────┬──────────┬───────┬────────┐"
    printf "│ %-32s │ %-8s │ Local │ Remote │\n" "Repository Path" "Branch"
    echo "├──────────────────────────────────┼──────────┼───────┼────────┤"
    for entry in "${repos_diverged[@]}"; do
        IFS='|' read -r repo branch local_c remote_c <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 32 ]; then
            repo="...${repo: -29}"
        fi
        if [ ${#branch} -gt 8 ]; then
            branch="${branch:0:7}…"
        fi
        printf "│ %-32s │ %-8s │ %5s │ %6s │\n" "$repo" "$branch" "$local_c" "$remote_c"
    done
    echo "└──────────────────────────────────┴──────────┴───────┴────────┘"
    echo ""
    echo -e "${BLUE}ⓘ${NC} These repos have local commits AND remote has new commits."
    echo -e "${BLUE}ⓘ${NC} Resolve manually or add to ignore list with: ./add_to_ignore.sh <path>"
    echo ""
else
    echo -e "${GREEN}✓ No repositories have diverged history${NC}\n"
fi

# Report 4: Repositories with uncommitted changes (that were committed and pushed)
if [ ${#repos_with_uncommitted[@]} -gt 0 ]; then
    echo -e "${YELLOW}Repositories With WIP Commits (Auto-committed):${NC}"
    echo "┌──────────────────────────────────────────────────┬──────────────┐"
    printf "│ %-48s │ %-12s │\n" "Repository Path" "Branch"
    echo "├──────────────────────────────────────────────────┼──────────────┤"
    for entry in "${repos_with_uncommitted[@]}"; do
        IFS='|' read -r repo branch <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 48 ]; then
            repo="...${repo: -45}"
        fi
        if [ ${#branch} -gt 12 ]; then
            branch="${branch:0:11}…"
        fi
        printf "│ %-48s │ %-12s │\n" "$repo" "$branch"
    done
    echo "└──────────────────────────────────────────────────┴──────────────┘"
    echo ""
else
    echo -e "${GREEN}✓ No repositories had uncommitted changes${NC}\n"
fi

# Report 3: Successfully pushed repositories
if [ ${#repos_pushed[@]} -gt 0 ]; then
    echo -e "${GREEN}Successfully Pushed Repositories:${NC}"
    echo "┌───────────────────────────────────────────┬──────────┬─────────┐"
    printf "│ %-41s │ %-8s │ %-7s │\n" "Repository Path" "Branch" "Pushed"
    echo "├───────────────────────────────────────────┼──────────┼─────────┤"
    for entry in "${repos_pushed[@]}"; do
        IFS='|' read -r repo branch commits <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 41 ]; then
            repo="...${repo: -38}"
        fi
        if [ ${#branch} -gt 8 ]; then
            branch="${branch:0:7}…"
        fi
        printf "│ %-41s │ %-8s │ %7s │\n" "$repo" "$branch" "$commits"
    done
    echo "└───────────────────────────────────────────┴──────────┴─────────┘"
    echo ""
fi

# Report: Bitbucket/GitLab to GitHub migrations
if [ ${#repos_bitbucket_mirrored[@]} -gt 0 ]; then
    echo -e "${GREEN}Repositories Migrated to GitHub (from Bitbucket/GitLab):${NC}"
    echo "┌───────────────────────────────────────┬────────────────┬──────────┐"
    printf "│ %-37s │ %-14s │ %-8s │\n" "Repository Path" "GitHub Repo" "From"
    echo "├───────────────────────────────────────┼────────────────┼──────────┤"
    for entry in "${repos_bitbucket_mirrored[@]}"; do
        IFS='|' read -r repo repo_name github_url service <<< "$entry"
        # Default to Bitbucket if service not specified (backward compatibility)
        if [ -z "$service" ]; then
            service="Bitbucket"
        fi
        # Truncate long paths if necessary
        if [ ${#repo} -gt 37 ]; then
            repo="...${repo: -34}"
        fi
        if [ ${#repo_name} -gt 14 ]; then
            repo_name="${repo_name:0:13}…"
        fi
        printf "│ %-37s │ %-14s │ %-8s │\n" "$repo" "$repo_name" "$service"
    done
    echo "└───────────────────────────────────────┴────────────────┴──────────┘"
    echo ""
fi

# Report: HTTPS to SSH conversions
if [ ${#repos_https_converted[@]} -gt 0 ]; then
    echo -e "${GREEN}HTTPS URLs Converted to SSH:${NC}"
    echo "┌────────────────────────────────────────────────────────────────┐"
    printf "│ %-62s │\n" "Repository Path"
    echo "├────────────────────────────────────────────────────────────────┤"
    for entry in "${repos_https_converted[@]}"; do
        IFS='|' read -r repo old_url new_url <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 62 ]; then
            repo="...${repo: -59}"
        fi
        printf "│ %-62s │\n" "$repo"
    done
    echo "└────────────────────────────────────────────────────────────────┘"
    echo ""
fi

# Report: Ignored repositories
if [ ${#repos_ignored[@]} -gt 0 ]; then
    echo -e "${BLUE}Ignored Repositories (from $IGNORE_FILE):${NC}"
    echo "┌────────────────────────────────────────────────────────────────┐"
    printf "│ %-62s │\n" "Repository Path"
    echo "├────────────────────────────────────────────────────────────────┤"
    for repo in "${repos_ignored[@]}"; do
        # Truncate long paths if necessary
        if [ ${#repo} -gt 62 ]; then
            repo="...${repo: -59}"
        fi
        printf "│ %-62s │\n" "$repo"
    done
    echo "└────────────────────────────────────────────────────────────────┘"
    echo ""
fi

# Report: Push failures (authentication/network issues)
if [ ${#repos_push_failed[@]} -gt 0 ]; then
    echo -e "${RED}⚠ Repositories With Push Failures (Auth/Network Issues):${NC}"
    echo "┌──────────────────────────────────────────┬──────────────────────┐"
    printf "│ %-40s │ %-20s │\n" "Repository Path" "Type"
    echo "├──────────────────────────────────────────┼──────────────────────┤"
    for entry in "${repos_push_failed[@]}"; do
        IFS='|' read -r repo type url <<< "$entry"
        # Truncate long paths if necessary
        if [ ${#repo} -gt 40 ]; then
            repo="...${repo: -37}"
        fi
        if [ ${#type} -gt 20 ]; then
            type="${type:0:19}…"
        fi
        printf "│ %-40s │ %-20s │\n" "$repo" "$type"
    done
    echo "└──────────────────────────────────────────┴──────────────────────┘"
    echo ""
    echo -e "${YELLOW}⚠ These repositories could not be pushed - likely SSH key issues${NC}"
    echo -e "${BLUE}ⓘ${NC} Verify your SSH keys are added to GitHub: https://github.com/settings/keys"
    echo -e "${BLUE}ⓘ${NC} Test SSH connection: ${YELLOW}ssh -T git@github.com${NC}"
    echo ""
fi

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Script completed!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"

# Print summary statistics
echo -e "\n${BLUE}SUMMARY STATISTICS:${NC}"
echo -e "┌─────────────────────────────────────────────────┬────────┐"
printf "│ %-47s │ %6s │\n" "Metric" "Count"
echo -e "├─────────────────────────────────────────────────┼────────┤"
printf "│ %-47s │ %6d │\n" "Total repositories found" "$total_repos_found"
printf "│ %-47s │ %6d │\n" "Repositories checked (not ignored)" "$total_repos_checked"
printf "│ %-47s │ %6d │\n" "Repositories ignored" "${#repos_ignored[@]}"
echo -e "├─────────────────────────────────────────────────┼────────┤"
printf "│ %-47s │ %6d │\n" "1. Without remotes" "${#repos_no_remote[@]}"
printf "│ %-47s │ %6d │\n" "2. Behind remote (need pull)" "${#repos_behind_remote[@]}"
printf "│ %-47s │ %6d │\n" "3. Pushed to remote" "${#repos_pushed[@]}"
printf "│ %-47s │ %6d │\n" "4. WIP commits created and pushed" "${#repos_with_uncommitted[@]}"
printf "│ %-47s │ %6d │\n" "5. Diverged history (not pushed)" "${#repos_diverged[@]}"
printf "│ %-47s │ %6d │\n" "6. Push failures (auth/network)" "${#repos_push_failed[@]}"
echo -e "├─────────────────────────────────────────────────┼────────┤"
printf "│ %-47s │ %6d │\n" "Bitbucket/GitLab repos migrated to GitHub" "${#repos_bitbucket_mirrored[@]}"
printf "│ %-47s │ %6d │\n" "HTTPS URLs converted to SSH" "${#repos_https_converted[@]}"
printf "│ %-47s │ %6d │\n" "GitHub repos created this run" "$github_repos_created"
echo -e "└─────────────────────────────────────────────────┴────────┘"

# Print ignore file location hint if there were authentication issues
if [ ${#repos_https_converted[@]} -gt 0 ]; then
    echo -e "\n${YELLOW}Note:${NC} HTTPS URLs were converted to SSH."
    echo -e "If you still get authentication errors, add the repo to: ${YELLOW}$IGNORE_FILE${NC}"
fi

# Final recommendations section
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}                    RECOMMENDATIONS                             ${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Build list of repos to consider ignoring
declare -a repos_to_consider_ignoring=()

# Add diverged repos
for entry in "${repos_diverged[@]}"; do
    IFS='|' read -r repo rest <<< "$entry"
    relative_path="${repo#$HOME/code/}"
    repos_to_consider_ignoring+=("$relative_path|Diverged history")
done

# Add repos that are only behind (external repos you don't maintain)
for entry in "${repos_behind_remote[@]}"; do
    IFS='|' read -r repo branch commits <<< "$entry"
    # Check if this repo is NOT in diverged or pushed lists (meaning it's just behind)
    is_diverged=false
    for div_entry in "${repos_diverged[@]}"; do
        IFS='|' read -r div_repo rest <<< "$div_entry"
        if [ "$repo" == "$div_repo" ]; then
            is_diverged=true
            break
        fi
    done
    
    is_pushed=false
    for push_entry in "${repos_pushed[@]}"; do
        IFS='|' read -r push_repo rest <<< "$push_entry"
        if [ "$repo" == "$push_repo" ]; then
            is_pushed=true
            break
        fi
    done
    
    # If only behind (not diverged and not pushed), might be external repo
    if ! $is_diverged && ! $is_pushed && [ "$commits" -gt 100 ]; then
        relative_path="${repo#$HOME/code/}"
        repos_to_consider_ignoring+=("$relative_path|Behind by $commits commits (external repo?)")
    fi
done

# Show recommendations
if [ ${#repos_to_consider_ignoring[@]} -gt 0 ]; then
    echo -e "${YELLOW}Repositories to Consider Adding to Ignore List:${NC}"
    echo -e "These repos may be external/forked repos you don't maintain:\n"
    
    for entry in "${repos_to_consider_ignoring[@]}"; do
        IFS='|' read -r path reason <<< "$entry"
        echo -e "  ${YELLOW}•${NC} ${path}"
        echo -e "    ${BLUE}Reason:${NC} ${reason}"
        echo -e "    ${GREEN}Command:${NC} ./add_to_ignore.sh $path"
        echo ""
    done
else
    echo -e "${GREEN}✓ No repositories need to be added to ignore list${NC}\n"
fi

# Show repos with unpushed changes (WIP commits that failed to push)
declare -a unpushed_wip=()
for wip_entry in "${repos_with_uncommitted[@]}"; do
    IFS='|' read -r wip_repo wip_branch <<< "$wip_entry"
    
    # Check if this repo was successfully pushed
    was_pushed=false
    for push_entry in "${repos_pushed[@]}"; do
        IFS='|' read -r push_repo rest <<< "$push_entry"
        if [ "$wip_repo" == "$push_repo" ]; then
            was_pushed=true
            break
        fi
    done
    
    # Check if it's in diverged list
    is_diverged=false
    for div_entry in "${repos_diverged[@]}"; do
        IFS='|' read -r div_repo rest <<< "$div_entry"
        if [ "$wip_repo" == "$div_repo" ]; then
            is_diverged=true
            break
        fi
    done
    
    # If WIP commit was created but not pushed and not diverged, it's a problem
    if ! $was_pushed && ! $is_diverged; then
        unpushed_wip+=("$wip_repo|$wip_branch")
    fi
done

if [ ${#unpushed_wip[@]} -gt 0 ]; then
    echo -e "${RED}⚠ Repositories With Unpushed WIP Commits:${NC}"
    echo -e "These repos have WIP commits that failed to push:\n"
    
    for entry in "${unpushed_wip[@]}"; do
        IFS='|' read -r repo branch <<< "$entry"
        relative_path="${repo#$HOME/code/}"
        echo -e "  ${RED}•${NC} ${relative_path} (${branch})"
        echo -e "    ${YELLOW}Action needed:${NC} Manually push or resolve conflicts"
        echo ""
    done
else
    echo -e "${GREEN}✓ All WIP commits were successfully pushed${NC}\n"
fi

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
